[package]
name = "wind"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
rsa = "0.9"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
base64 = "0.21"
rand = "0.8"
